#!/usr/bin/env bash
#
# Build the applications listed in tools/apps.tsv and publish them into this
# repository, recording where each one came from.
#
#   tools/sync-apps.sh            build + copy + stamp every app
#   tools/sync-apps.sh cutlist    just one
#   tools/sync-apps.sh --check    no build: is anything stale? (exit 1 if so)
#
# The problem this solves is not copying files — it is that a copied file gives
# no way to tell whether what is deployed matches its source. Every app gets a
# SOURCE file naming the commit it was built from.

set -euo pipefail
cd "$(dirname "$0")/.."

MANIFEST=tools/apps.tsv
CHECK=0
ALLOW_DIRTY=0
ONLY=""

for arg in "$@"; do
  case "$arg" in
    --check)       CHECK=1 ;;
    --allow-dirty) ALLOW_DIRTY=1 ;;
    -h|--help)     sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*)            echo "unknown flag: $arg" >&2; exit 2 ;;
    *)             ONLY="$arg" ;;
  esac
done

# macOS ships shasum, most Linuxes sha256sum.
sha() { if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1
        else shasum -a 256 "$1" | cut -d' ' -f1; fi; }

# Hash a whole directory deterministically, so directory artifacts work too.
sha_tree() {
  find "$1" -type f -print0 | LC_ALL=C sort -z | xargs -0 cat | \
    { if command -v sha256sum >/dev/null; then sha256sum; else shasum -a 256; fi; } | cut -d' ' -f1
}

fingerprint() { [ -d "$1" ] && sha_tree "$1" || sha "$1"; }

# Trim leading/trailing whitespace. Not xargs: it parses quotes, and the
# manifest's comments contain them.
trim() { local v="$1"; v="${v#"${v%%[![:space:]]*}"}"; printf '%s' "${v%"${v##*[![:space:]]}"}"; }

red() { printf '\033[31m%s\033[0m\n' "$*"; }
dim() { printf '\033[2m%s\033[0m\n' "$*"; }

stale=0
count=0

while IFS='|' read -r slug repo build artifact; do
  slug=$(trim "${slug:-}");         [ -z "$slug" ] && continue
  repo=$(trim "${repo:-}")
  build=$(trim "${build:-}")
  artifact=$(trim "${artifact:-}")
  [ -n "$ONLY" ] && [ "$ONLY" != "$slug" ] && continue
  count=$((count + 1))

  repo_as_written="$repo"          # SOURCE records this, not the expanded
  repo="${repo/#\~/$HOME}"         # path, which would leak $HOME publicly
  if [ ! -d "$repo" ]; then red "✗ $slug: source repo not found: $repo"; stale=1; continue; fi

  src_commit=$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo "uncommitted")
  dirty=""
  if [ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]; then dirty=" (dirty)"; fi

  # ── --check: compare what is published against where the source is now ──
  if [ "$CHECK" = 1 ]; then
    if [ ! -f "$slug/SOURCE" ]; then red "✗ $slug: never synced"; stale=1; continue; fi
    was=$(awk '$1=="commit"{print $2}' "$slug/SOURCE")
    rec=$(awk '$1=="sha256"{print $2}' "$slug/SOURCE")
    target="$slug"; [ -f "$slug/index.html" ] && [ ! -d "$slug/assets" ] && target="$slug/index.html"
    now=$(fingerprint "$target")
    if [ "$now" != "$rec" ]; then
      red "✗ $slug: published files edited by hand since last sync"; stale=1
    elif [ "$was" != "$src_commit" ] || [ -n "$dirty" ]; then
      red "✗ $slug: source moved on (published $was, source now $src_commit$dirty)"; stale=1
    else
      echo "✓ $slug: up to date ($src_commit)"
    fi
    continue
  fi

  # ── sync ──
  if [ -n "$dirty" ] && [ "$ALLOW_DIRTY" = 0 ]; then
    red "✗ $slug: $repo has uncommitted changes."
    red "  Publishing from a dirty tree means SOURCE would name a commit that"
    red "  does not contain what you shipped. Commit there, or --allow-dirty."
    stale=1; continue
  fi

  dim "→ $slug: building in $repo"
  ( cd "$repo" && eval "$build" ) >/dev/null

  src="$repo/$artifact"
  [ -e "$src" ] || { red "✗ $slug: build produced no $artifact"; stale=1; continue; }

  mkdir -p "$slug"
  if [ -d "$src" ]; then
    rm -rf "${slug:?}"/* && cp -R "$src"/. "$slug"/
    target="$slug"
  else
    cp "$src" "$slug/index.html"
    target="$slug/index.html"
  fi

  cat > "$slug/SOURCE" <<EOF
# Generated by tools/sync-apps.sh — do not edit, and do not hand-edit the
# published files either: --check compares them against this hash.
app       $slug
source    $repo_as_written
commit    $src_commit$dirty
built     $(date -u +%Y-%m-%dT%H:%M:%SZ)
artifact  $artifact
sha256    $(fingerprint "$target")
EOF

  echo "✓ $slug: published from $src_commit$dirty ($(du -h "$target" | cut -f1))"
done < <(grep -vE '^[[:space:]]*(#|$)' "$MANIFEST")

[ "$count" = 0 ] && { red "no app matched${ONLY:+ '$ONLY'}"; exit 2; }
exit "$stale"
